{% set name = "agate-sql" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b1b30284a573fd416759437273dcc5c81022bdf2facb24b4aa029a62afd53b0

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - agate >=1.5.0
    - sqlalchemy >=1.4

# E   Module not found "sqlalchemy-cratedb"
{% set deselect_tests = " --deselect=tests/test_agatesql.py::TestSQL::test_to_sql_create_statement_with_dialects" %}

test:
  source_files:
    - tests
  imports:
    - agatesql
  commands:
    - pip check
    - pytest -v tests {{ deselect_tests }}
  requires:
    - pip
    - pytest

about:
  home: https://agate-sql.readthedocs.org
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'agate-sql adds SQL read/write support to agate.'
  description: |
    agate-sql uses a monkey patching pattern to add SQL support to all agate.Table instances.
  doc_url: https://agate-sql.readthedocs.org
  dev_url: https://github.com/wireservice/agate-sql

extra:
  recipe-maintainers:
    - pmlandwehr
