travis:
  secure:
    BINSTAR_TOKEN: k8c/luyKpyj0iMQHU1yWrvJqjbCXefdiydNmQRQZFs9mZyFqPru+ewIjkGrnbjbh0gIRMaQQWq4YxjGRv5SK6fH0hx1EmWPZDFu6YbsP8o71rJITfEJVP1NkOznpqePKYBiTKwRAVi5Ho6drZLDiKF7PBB8szBSBV1m0VWY70Scg+fCjRV9a4bbMVFoRbbLgyaAY1li5VqBbD2KNH1VZvJfiC17vb/nIR7clJkfiUyXfYQ2aneFrRhWZJa93+dE/VKAmFrpUwoV1hDJgoqWfOdx4vVxoQDylS54M6+bgG3r9a8lURnt/SvY2cTinuvnYz+T1hGGBMndPY+4Fiu4k5mzcy7XrjlUEBnWslZ9d4KYWNoiVwpVqwHRA+YEivPwm88hbJ3Sz1DZC1FrNP0QwVZn4vfsRycK+RK+qSunrHmSk0xCrC31ApcSp49pGMYZnPwe0DjbFxAoK64Frr/GD0pu+VTyT5dG2ecjoVFMozmYAvLqnBkz3DPBleDaErY2zlbe9gwBZSmU2ZmlrDh5Azgpta0asLgrzPTyAfxPkMm6Y5i2Z8utD7Hl14p1iJylrUHYqKwKA5R2y/UPnMD0Y42l0c3axVt0mP2Hie6q+MmjGGjoPwHXRtIq2TCKD97Nq4ga++g3jXlO6Kg/Xey7vFljBzogZlO+fbaA0XX0JzcM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
