travis:
  secure:
    BINSTAR_TOKEN: Pv6HNmP25V+sVrqzppQje236zXF6tNjOAOO33Wdu6fUKZAfo6w1l0wQMRgIDkGduAfW0C10YPCEfWwMFxFYKhsl+7KnLgS2Nw8xyaEcqC1V741QpudYEJEqY2MngLFvd4O6ABBgqY/FXQIWU3183mls+wKNxeIMpp9/YfDcyP9wZqreLLNrzV37Xh32Lz645QK2AcLHh8QhA15UdDcdSca2DLov3GdP0o2XnhN+YAeRi/PsuBM/fRVEJ18vRcKyS2wldCSw4yEP3kOq2gOFo4pfo1PwOr90fvsXudM9z5J1bZlJ0NsVVb2qz1ozyZFGG2hvvepQjv0miq+9mbKDLz9IcESVcMfDUj/prI43j44RAeisqdWM3NOHDFzS1CGSwzQOwv8V9Rq4cmJfi4xuIJUYpdi6BG5VvkCYTLrMWrNJzbp/Ud/QItco5xcEn0FF5CcBWWP9SNmn9MhFvokjrlITqBlBk5m8MKDElUFtW7E+COxqWWBV9S9wkosdkHgAsb5EuqkZu6YIz8bBMV/GYagXYkav51VL36l57jaxl+DfoOKdzX6cSK1mA0rAvmE46YPQa3/OZ/pPQfN3vcQfhrqUTBnGpweetVPACk6uyH1Ta/IBvisSamQF6b0jtHaeuffMG+laN29h9IVlJvEKwGVqu2Qr3u9xs+Nw5Q5rzv90=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
