travis:
  secure:
    BINSTAR_TOKEN: YiKpcbcw0JezOY2zxTL9ecMDHVRPUjXQMx2GftTUAsMR5xtyaBZ7ezBx6qYcH2jr7R6gsvgXWA9MxQt6qTcS86NzSXPocmjCoCMse7QRwbqLBa84a351tFskNKFADe9WD3BWuId3ucaaY+0e7Y69WO0PmQeUwHbXgJfsC0qehoc52o5QPp3Bs6aFJFECZeGsthYft8PuBDcQZODhsAXWCl7ZJfA+fjAFil4SuVHtWz4v6MsDLXh3nj1rg/Rc0o3TGotny15Au261Sl1aDSjqWqPLbrZo3CyDxPVGtkOyw1oiylxYu+CqJjXV6ROOjqYTW9kcjSghhV/AyzMtw+4NfQfrpk1XY/Zg0eXS96/YCJQrZDbPoOFwLI9OLsCLCSSGm7Z+GO4oWQ3j7uLfnox7rI+w80VWzRXKN2548sG86ElsUcrn3uI6+EZW6dLyWynjyTW15VUyimiunuAGT+SZ7esbP+Irkriv6ZeWFqHhUmlrQqvfteGwMJLx/n4Rv7/+CnoF5WvuNozXc8f6DxtWsasvdxZy8RYKLBBv01FT/2YLdppFVoPuHklhOSdCZaDO92WqPgimSZ8R4Hor9bW30U7T2HKVLXXIk7cVGXp/wBWgOvVe3K9j/+2kUY8cQBAdkkKtjlLPppv4ouPgETvnVbcMmuxKjNdC70yIboHDWEM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
