travis:
  secure:
    BINSTAR_TOKEN: jDmWf5qhcV6c2641BWdreCg+IR6D52uVJs5jvbYq0yRcnLqs+aJSIiu4/prU3HfSYF/SPUIvFqymhGgXWlseSE7hYXBuC61wRb7H3YvjqJZHRjzjraV3/02p1ugSaGj2eyBVi1yod7nm99UPG6IAuOoox/SEbtuNdXCZznrgDZuN+LWKr4HfJCUUSXIIvmW/1b4COscvilGFg67FTk3rla7N/BgLS0+Dn257jmxPNxLnXY6uOC84/ctxjwmtFUNO4J1Pd3JXJhGKzJWHBvnzshguO/WTSkhBIbS/vT8LHr6VFT8XUoWG/wFWPBan7hdL93GR5Vwsk5U2S0PuGAfdwhbIA2IAKQYkHa3TNQxWlpQGLHJsoWNm2X5+vx/x4dS3ASN/SIfVpgowLtx9VlSRMq+QAmWItWo9AUQUtVp5Yec6bxC6Vi0A/9EJiOf28DXDwajOQDCMo3Zm2WAOiXR8eKybKJIPV6ecAkngssmFSplLJtQIhOAcB9NVXqkRf9Lo+39R0bdM4Eh9T+S7M+9/KhiNqUMtnnNuVMen9iGYe5MTCjROF4B1jwTrq+4qE09Q6xjcx6bLHs2G6GjgZhZEJYtspvWx9aNXV+kZVyq6DHq8v0R3JN2eO7/OhNxOd/mZSSr/Xk7jA35MIlG43RCiW1UayqXFwU9GOKfjsbFt8Ks=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
